### ISSUE TITLE
Obtaining offsets for the AI-driven cars

### ISSUE THREAD

**Issue by zappybiby** [nlhans/SimShift#4]
Hello @nlhans,

I know that you have that this project is now deprecated, but I was hoping to find out how you went about obtaining the memory offsets for the AI cars that you used in `Ets2DataMiner.cs`

I know how to obtain offsets with Cheat Engine by finding the offset of a known variable (e.g. my truck's speed) and looking at the nearby addresses to find other information about my truck (that might not be covered by the SDK). Then there's also the pointer scanner feature in CE which I've used to find things based off the approximations of their value (e.g. value is now positive/negative). However, in the case of the AI cars, I'm not sure how I would go about finding their offsets as I don't really have anything to start from that relates to them?

**Comment by nlhans** [comment]
This was not an easy thing to do, and is actually the most breaking thing of the ACC system.

I cannot give a strict procedure, just other than say be smart. Thinking logically, I figured that a car must have a speed variable in memory, so I found an AI car and made it stop (e.g. block or crash into it), then looking for floats that decreased, and when it got going again look for floats that increased.
Iterate this as many times as needed. Restart as many times as needed if you messed up somewhere (or eg the AI despawns because it drives into a road you cannot drive onto).

Based on this info, you could use the debugger to deduce the pointer offsets the game uses, and reverse engineer the memory structure to a satisfactory degree.

**Comment by zappybiby** [comment]
I was able to obtain the offsets of an AI vehicle's speed by doing a series of scans for a float value between an estimated range of the speed of the vehicle. Each time I did this I got a total of four to five addresses that I assume are the values of the cars behind me. I then looked at what wrote to those addresses and obtained the 'best guess' from CE. I then ran a pointer scan on the 'best guess' address and re-scanned multiple times to get the pointer to that address. 

At the moment I have the pointer for the speed of the nearest AI vehicle (just to save time - I have the values of the other cars as well) but after dissecting its data structure I'm not seeing anything related to it's coordinates. What I will try to do is record the coordinates of my truck in a certain position and then have the AI car behind me drive to that approximate location. Hopefully I can get the pointer for the coordinates that way.

Thanks for your assistance with this issue.

**Comment by ztl2004** [comment]
> I was able to obtain the offsets of an AI vehicle's speed by doing a series of scans for a float value between an estimated range of the speed of the vehicle. Each time I did this I got a total of four to five addresses that I assume are the values of the cars behind me. I then looked at what wrote to those addresses and obtained the 'best guess' from CE. I then ran a pointer scan on the 'best guess' address and re-scanned multiple times to get the pointer to that address.
> 
> At the moment I have the pointer for the speed of the nearest AI vehicle (just to save time - I have the values of the other cars as well) but after dissecting its data structure I'm not seeing anything related to it's coordinates. What I will try to do is record the coordinates of my truck in a certain position and then have the AI car behind me drive to that approximate location. Hopefully I can get the pointer for the coordinates that way.
> 
> Thanks for your assistance with this issue.

hello guys, 

is this problem solved or so? could it be possible that share a bit of info with me, thanks 
pretty interested in finding the cords of AI cars

Thanks a lot!
